import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import Sidebar from "@/components/Layout/Sidebar";
import Login from "@/components/PageComponent/Login";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get cookie from server side
  const token = cookies()?.get("user")?.value;

  return (
    <html lang="en">
      <body className={inter.className}>
        {token ? <Sidebar>{children}</Sidebar> : <Login />}
      </body>
    </html>
  );
}
